# Informações básicas do site
title: "Arroz e Flores"
description: "Antologia de literatura rebelde japonesa em tradução para o português"
url: "https://arrozeflores.art.br"
permalink: /:slug/
author: "Arroz e Flores"

# Plugins
plugins:
  - jekyll-sitemap

sitemap:
  exclude:
    - /404.html
  path: /sitemap.xml

